import { test, expect } from '@playwright/test';

test('request', async ({ page }) => {
  await page.goto('https://mms-frontend.herokuapp.com/signIn');
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').fill('info@esoftresponse.com');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('password');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.pause()
  await page.getByRole('link', { name: 'Request' }).click();
  await page.getByRole('tab', { name: 'Pending (0)' }).click();
  await page.getByRole('tab', { name: 'Accepted (0)' }).click();
  await page.getByRole('tab', { name: 'Declined (0)' }).click();
  await page.getByRole('searchbox', { name: 'Search by name' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.locator('.css-19bb58m').first().click();
  await page.getByText('Christian Ecom', { exact: true }).click();
  await page.locator('.select__input-container').click();
  await page.locator('#react-select-3-option-0').click();
  await page.locator('#chakra-modal--body-25 svg').nth(2).click();
  await page.getByLabel('Close').click();
  await page.getByRole('tab', { name: 'Naming' }).click();
  await page.getByRole('tab', { name: 'Pending (2)' }).click();
  await page.getByRole('tab', { name: 'Accepted (0)' }).click();
  await page.getByRole('tab', { name: 'Declined (0)' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.locator('.css-19bb58m').first().click();
  await page.locator('#officiatingPastor svg').click();
  await page.locator('div').filter({ hasText: /^Child's Full Name$/ }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByLabel('Close').click();
  await page.getByRole('tab', { name: 'Child Dedication' }).click();
  await page.getByRole('tab', { name: 'Pending (0)' }).click();
  await page.getByRole('tab', { name: 'Accepted (0)' }).click();
  await page.getByRole('tab', { name: 'Declined (0)' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.locator('.css-1xc3v61-indicatorContainer').first().click();
  await page.locator('.css-15lsz6c-indicatorContainer').click();
  await page.locator('div').filter({ hasText: /^Child's Full Name$/ }).click();
  await page.locator('.css-1l9rpdi > .css-b62m3t-container > .css-13cymwt-control > .css-1wy0on6 > .css-1xc3v61-indicatorContainer').click();
  await page.locator('.css-15lsz6c-indicatorContainer').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByLabel('Close').click();
  await page.getByRole('tab', { name: 'Prayer' }).click();
  await page.getByRole('tab', { name: 'Pending (0)' }).click();
  await page.getByRole('tab', { name: 'Accepted (0)' }).click();
  await page.getByRole('tab', { name: 'Declined (0)' }).click();
  await page.getByRole('tab', { name: 'Baptism' }).click();
  await page.getByRole('tab', { name: 'Pending (1)' }).click();
  await page.getByRole('tab', { name: 'Accepted (0)' }).click();
  await page.getByRole('tab', { name: 'Declined (0)' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.locator('.css-1xc3v61-indicatorContainer').click();
  await page.locator('.css-15lsz6c-indicatorContainer').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByLabel('Close').click();
  await page.getByRole('button', { name: 'Export' }).click();
  await page.locator('.chakra-checkbox__control').first().click();
  await page.locator('div:nth-child(4) > .chakra-checkbox > .chakra-checkbox__control').click();
  await page.locator('div:nth-child(5) > .chakra-checkbox > .chakra-checkbox__control').click();
  await page.locator('div:nth-child(6) > .chakra-checkbox > .chakra-checkbox__control').click();
  await page.locator('div:nth-child(7) > .chakra-checkbox > .chakra-checkbox__control').click();
  await page.locator('div:nth-child(8) > .chakra-checkbox > .chakra-checkbox__control').click();
  await page.locator('div:nth-child(9) > .chakra-checkbox > .chakra-checkbox__control').click();
  await page.locator('div:nth-child(9) > .chakra-checkbox > .chakra-checkbox__control > div > .css-1r69mki').click();
  await page.locator('div:nth-child(8) > .chakra-checkbox > .chakra-checkbox__control > div').click();
  await page.locator('div:nth-child(7) > .chakra-checkbox > .chakra-checkbox__control').click();
  await page.locator('div:nth-child(6) > .chakra-checkbox > .chakra-checkbox__control > div').click();
  await page.locator('div:nth-child(4) > .chakra-checkbox > .chakra-checkbox__control > div > .css-1r69mki').click();
  await page.getByLabel('Baptism').locator('svg').nth(1).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download' }).click();
  const download = await downloadPromise;
});